require 'rubygems'
require 'selenium'
require 'test/unit'
require 'test/unit/ui/testrunnermediator'
require 'timeout'
require 'rake'
require 'rake/testtask'

require 'selenium_rails/adapters/test_unit'
require 'selenium_rails/selenium_driver_manager'
require 'selenium_rails/selenium_helper'
require 'selenium_rails/selenium_test_case'
require 'selenium_rails/servers_runner'
load 'selenium_rails/tasks/selenium_tasks.rake'
